### PR TITLE
Fix open fold after undo

### PR DESCRIPTION
**Pull request by lacygoill**
This PR tries to fix the issue [#80](https://github.com/tpope/vim-repeat/issues/80).

### CODE REVIEW

**Comment by lacygoill** [comment]
Actually, the simplest and more reliable fix is to just get rid of `zv`, and pass the `t` flag to `feedkeys()`, so that the `u` key is not processed as if it came from a mapping.  Is there a reason why the `t` flag was not used originally?  Is it because it was not implemented at the time the plugin was written?  It works on v7.3.001.

If you want me to push a new commit, let me know.

**Comment by tpope** [comment]
That reason is correct, and while 7.3 is ancient history at this point, I still try not to break Vim backwards compatibility without a good reason. A simple `v:version >= 703 ? 'nt' : 'n'` would satisfy my requirements.

**Comment by lacygoill** [comment]
Actually, the `t` flag causes another issue.  During a recording, `t` would cause the undo command to be recorded twice.  So the original fix was probably better.

**Comment by lacygoill** [comment]
I'm closing the PR because the proposed fix causes another issue; it prevents `u`, `U`, and `C-r` from printing some info about the undo state, as reported in #27.

One solution would be to install a fire-once autocmd listening to `TextChanged`, which would execute `zv` only on the condition that the cursor is inside a closed fold:
```diff
diff --git a/autoload/repeat.vim b/autoload/repeat.vim
index 708c318..1db2b86 100644
--- a/autoload/repeat.vim
+++ b/autoload/repeat.vim
@@ -132,10 +132,12 @@ endfunction
 function! repeat#wrap(command,count)
     let preserve = (g:repeat_tick == b:changedtick)
     call feedkeys((a:count ? a:count : '').a:command, 'n')
-    exe (&foldopen =~# 'undo\|all' ? 'norm! zv' : '')
     if preserve
         let g:repeat_tick = b:changedtick
     endif
+    au TextChanged <buffer> if &foldopen =~# 'undo\|all' && foldclosed('.') != -1
+        \ |     call feedkeys('zv', 'in')
+        \ | endif
 endfunction
 
 nnoremap <silent> <Plug>(RepeatDot)      :<C-U>exe repeat#run(v:count)<CR>
```
But I think this patch would cause a merge conflict with the patch proposed in #79.  If the latter is merged, I think I could then suggest a patch fixing the issue.

Anyway, for anyone interested, here is [my current fix](https://github.com/lacygoill/vim-repeat/blob/6c8dfa2a3f9a07aa0ad0f10c13f520b4815a2f00/autoload/repeat.vim#L568-L582) on the fork I'm using.

**Pull request closed without merging**
