### PR TITLE
Prevent stack trace of search errors.

### PR DESCRIPTION
**Pull request by orlp**
Solves https://github.com/tpope/vim-repeat/issues/38 , at least for searching (I tried to be conservative in filtering error messages - more can be added).

### CODE REVIEW

**Comment by orlp** [comment]
It might be also correct (and even better) to pattern match on `Vim(normal)`, I just took the most conservative route possible.

**Comment by tpope** [comment]
Can you change `call repeat#run` to `exe repeat#run` and the end of the function to look like:

```viml
catch ...
  let v:errmsg = ...
  return 'echoerr v:errmsg'
endtry
return ''
```

This makes the error more like a real Vim error.

**Comment by orlp** [comment]
@tpope Ok. Do you think I should use the conservative (but possibly incomplete) E-numbers just for searching, or `Vim(normal)` in to catch?

**Comment by tpope** [comment]
I think `Vim(normal)` is fine.

Setting `v:errmsg` is just a convenient global to make it available in the outer scope.

**Comment by orlp** [comment]
I'm not too familiar with Vim's scoping rules, but everything works fine by default - `v:errmsg` is already set.

Are you suggestiong I should do `let v:errmsg = v:errmsg`?

**Comment by tpope** [comment]
In the past I recall having to explicitly massage `v:exception` to get a suitable `v:errmsg`. But if you can get away without it, go for it.

**Comment by orlp** [comment]
@tpope Done.

**Comment by orlp** [comment]
@tpope  It's been a while now, can this be merged or do I need to change something?

**Comment by orlp** [comment]
@tpope  Thanks!

**Pull request merged**
